### ISSUE TITLE
Meta Intergrations 

### ISSUE THREAD

**Issue by bramtuuk** [REA-Eindhoven/wereldwinkel-nuenen#43]
- [x] Static caroussel instagram (desktop)
- [x] Static caroussel instagram (mobile)
- [x] Static caroussel instagram (mobile) swipe
- [x] Static nieuws facebook (desktop)
- [x] Static nieuws facebook (mobile)
- [ ] voorberijdend javascript schrijven
- [ ] Meta developer account opzetten
- [ ] keys linken
